### PR TITLE
Delete audio/music directory

### PR DESCRIPTION
**Pull request by StanleySweet**

### CODE REVIEW

**Comment by rossenburgg** [comment]
merged and rebuilt @StanleySweet

**Comment by StanleySweet** [comment]
Gotta upload it now. :) Might be better with a release tag :)

**Comment by andy5995** [comment]
@StanleySweet btw, if you ever decide you wanna use the artifact upload action, this is what happens:

(You see at the bottom is the archive created that can be downloaded and inspected if needed, without being added to the release page)

https://github.com/rossenburgg/godseye/actions/runs/3228958106

**Comment by StanleySweet** [comment]
@andy5995  My issue was that that's the one that was uploaded on 0ad.mod.io with the long commit name which isn't ideal IMHO :)

**Comment by StanleySweet** [comment]
@rossenburgg I made a custom version, it's now live and available on 0ad.mod.io.

**Comment by rossenburgg** [comment]
Thanks @StanleySweet! 💜 will check it out

**Pull request merged**
